# Generated by Django 4.2.6 on 2023-11-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_de_Posiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje final')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
    ]
