# Generated by Django 4.2.6 on 2023-11-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_de_posiciones',
            name='nombre_corredor',
            field=models.CharField(max_length=120, null=True, verbose_name='Nombre'),
        ),
    ]
