# Generated by Django 4.2.6 on 2023-11-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0002_tabla_de_posiciones_nombre_corredor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto_Matias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.DeleteModel(
            name='Tabla_de_Posiciones',
        ),
    ]
