# Generated by Django 4.2.6 on 2023-11-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0006_piloto_pato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto_Agustin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto_Cristian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto_Martincho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto_Pedro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
    ]
