# Generated by Django 4.2.6 on 2023-11-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0007_piloto_agustin_piloto_cristian_piloto_martincho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Carrera')),
                ('fecha', models.DateField(max_length=60, verbose_name='Fecha')),
                ('hora', models.DateField(max_length=60, verbose_name='Hora')),
                ('lugar', models.CharField(max_length=100, verbose_name='Pista')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Ganador')),
            ],
        ),
    ]
