# Generated by Django 4.2.6 on 2023-11-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0008_fechas_carreras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechas_carreras',
            name='hora',
            field=models.DateTimeField(max_length=60, verbose_name='Hora'),
        ),
    ]
