# Generated by Django 4.2.6 on 2023-11-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0009_alter_fechas_carreras_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechas_carreras',
            name='hora',
            field=models.TimeField(max_length=60, verbose_name='Hora'),
        ),
    ]
