# Generated by Django 4.2.7 on 2023-11-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0010_alter_fechas_carreras_hora'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piloto_Pedro',
            new_name='Piloto_Yoa',
        ),
        migrations.DeleteModel(
            name='Piloto_Agustin',
        ),
    ]
