# Generated by Django 4.2.7 on 2023-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebKarting', '0012_piloto_guada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto_Alejandro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto_Julian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
        migrations.CreateModel(
            name='Piloto_Nicolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.CharField(max_length=60, verbose_name='Puntaje actual')),
                ('carreras_ganadas', models.CharField(max_length=60, verbose_name='Carreras Ganadas')),
                ('fechas_completadas', models.CharField(max_length=60, verbose_name='Fechas Completadas')),
            ],
        ),
    ]
